### ISSUE TITLE
npm run build - files/fields names problem

### ISSUE THREAD

**Issue by programista-zacny** [hubject/oicp-cpo-2.3-api-doc#2]
Used latest Node LTS: `https://nodejs.org/dist/v18.14.0/node-v18.14.0-linux-x64.tar.xz`

Run command (from `README.md`):
```
npm run build
```

Output:
```
> cpo@1.0.0 build
> swagger-cli bundle src/openapi.yaml --outfile _build/openapi.yaml --type yaml && npm run copy-files

Error opening file "/path/oicp-cpo-2.3-api-doc/src/schemas/EvcoId.yaml" 
ENOENT: no such file or directory, open 'path/oicp-cpo-2.3-api-doc/src/schemas/EvcoId.yaml'
```
PS. I changed original path to `path` :)

I think files names can be a problem (or fields names). There is a file named `EvcoID.yaml`, not `EvcoId.yaml`.

**Comment by moghaffari** [comment]
#5 Fixed the issue
